@echo off
rem HttpShare WebDAV mount script (generated by the HttpShare app).
rem The cmd part must stay pure ASCII: cmd.exe mis-parses multi-byte lines in batch files.
rem Everything after the ##PS-BEGIN marker is PowerShell, read and run by the line below.
setlocal
set "HS_SELF=%~f0"
"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -Command "$t=[IO.File]::ReadAllText($env:HS_SELF,[Text.Encoding]::UTF8); iex $t.Substring($t.LastIndexOf([char]35+'#PS-BEGIN'))"
set "RC=%ERRORLEVEL%"
echo.
if not defined HTTPSHARE_NOPAUSE pause
exit /b %RC%
##PS-BEGIN
$ErrorActionPreference = 'Stop'
$DavUrl = '{URL}'
$Unc = '{UNC}'
$NeedBasic = {NEED_BASIC}
$Persist = '{PERSIST}'
$Note = '{NOTE}'
$Sys = Join-Path $env:SystemRoot 'System32'
$KeyPs = 'HKLM:\SYSTEM\CurrentControlSet\Services\WebClient\Parameters'
$KeyReg = 'HKLM\SYSTEM\CurrentControlSet\Services\WebClient\Parameters'
function Say([string]$t, [string]$c = 'Gray') { Write-Host (' ' + $t) -ForegroundColor $c }
function Fail([string]$t) { Write-Host; Say $t 'Red'; exit 1 }
function OpenDrive([string]$d) { if (-not $env:HTTPSHARE_NOPAUSE) { Start-Process explorer.exe "$d\" } }
try { $Host.UI.RawUI.WindowTitle = 'HttpShare WebDAV' } catch { }
try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch { }

Write-Host
Say 'HttpShare - 把手机挂载为网络盘' 'White'
Say ('地址：' + $DavUrl)
Write-Host

if (-not (Get-Service WebClient -ErrorAction SilentlyContinue)) {
    Fail '本机没有 WebClient（WebDAV 客户端）服务。Windows 服务器版需在“服务器管理器”中添加“WebDAV 重定向程序”功能，或改用 RaiDrive 等工具。'
}

# 发一个请求，返回 @(状态码, 错误类型, 说明)
function Probe([string]$auth) {
    try {
        $rq = [Net.HttpWebRequest]::Create($DavUrl)
        $rq.Method = 'GET'
        $rq.Timeout = 15000
        $rq.AllowAutoRedirect = $false
        if ($auth) { $rq.Headers['Authorization'] = 'Basic ' + $auth }
        $rs = $rq.GetResponse()
        $code = [int]$rs.StatusCode
        $rs.Close()
        return @($code, '', '')
    } catch [Net.WebException] {
        $e = $_.Exception
        if ($e.Response) { return @([int]$e.Response.StatusCode, '', '') }
        return @(0, [string]$e.Status, $e.Message)
    } catch {
        return @(0, 'Other', $_.Exception.Message)
    }
}

# 1. 先确认能连上手机、证书可用（不带密码，不计入错误次数）
$r = Probe ''
if ($r[0] -eq 0) {
    if ($r[1] -match 'TrustFailure|SecureChannelFailure') {
        Fail ('Windows 不信任 App 的自签名 HTTPS 证书，系统自带的网络盘无法挂载。' +
              '请在 App「设置」里关闭 HTTPS（局域网内用 HTTP），或在首页切换为「CF 隧道」，然后在网页上重新下载本脚本。')
    }
    Fail ('连不上手机（' + $r[2] + '）。请确认手机上的服务正在运行、电脑和手机在同一网络；外网隧道地址每次启动都会变，需重新下载脚本。')
}
if ($r[0] -eq 404) { Fail 'App 设置里关闭了 WebDAV，请先开启。' }

# 2. 已挂载过同一地址：直接打开
foreach ($l in (& "$Sys\net.exe" use 2>$null)) {
    if ($l -like "*$Unc*" -and $l -match '\b([A-Z]:)\s') {
        $d = $Matches[1]
        if (Test-Path "$d\") {
            Say "已挂载为 $d 盘，正在打开……" 'Green'
            OpenDrive $d
            exit 0
        }
    }
}

# 3. Windows WebDAV 设置：局域网 HTTP 需允许 HTTP 登录（BasicAuthLevel=2）；单文件上限默认 50 MB，改为 4 GB
function NeedFix {
    $p = Get-ItemProperty $KeyPs -ErrorAction SilentlyContinue
    $bal = if ($p) { $p.BasicAuthLevel } else { $null }
    $fsl = if ($p) { $p.FileSizeLimitInBytes } else { $null }
    $bad = @()
    if ($NeedBasic -and $bal -ne 2) { $bad += 'basic' }
    if (-not ($fsl -eq -1 -or $fsl -eq 4294967295)) { $bad += 'size' }
    return ,$bad
}
$bad = NeedFix
if ($bad.Count -gt 0) {
    Say '需要调整 Windows 的 WebDAV 设置（允许 HTTP 登录、单文件上限改为 4 GB），将弹出一次管理员权限确认……' 'Yellow'
    $fix = "$Sys\reg.exe add $KeyReg /v FileSizeLimitInBytes /t REG_DWORD /d 4294967295 /f"
    if ($NeedBasic) { $fix += " & $Sys\reg.exe add $KeyReg /v BasicAuthLevel /t REG_DWORD /d 2 /f" }
    $fix += " & $Sys\net.exe stop WebClient & $Sys\net.exe start WebClient"
    try { Start-Process "$Sys\cmd.exe" -ArgumentList "/c $fix" -Verb RunAs -Wait -WindowStyle Hidden } catch { }
    $bad = NeedFix
    if ($bad -contains 'basic') {
        Fail '未能修改设置（可能在管理员确认时点了“否”）。局域网 HTTP 地址必须允许 HTTP 登录才能挂载，请重新运行并点“是”。'
    }
    if ($bad -contains 'size') { Say '提示：单文件上限未修改，大于 50 MB 的文件可能无法通过资源管理器传输。' 'Yellow' }
}
& "$Sys\sc.exe" start WebClient 2>&1 | Out-Null
for ($i = 0; $i -lt 20 -and (Get-Service WebClient).Status -ne 'Running'; $i++) { Start-Sleep -Milliseconds 300 }

# 4. 输入并验证密码（先验证再挂载，提示更明确）
$pw = $null
$ok = $false
for ($try = 1; $try -le 3; $try++) {
    if ($env:HTTPSHARE_PW) {
        $pw = $env:HTTPSHARE_PW
    } else {
        $sec = Read-Host ' 请输入访问密码（App「设置」里可查看/复制，输入时不显示）' -AsSecureString
        $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec)
        try { $pw = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr) } finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
    }
    if (-not $pw) { Fail '未输入密码，已取消。' }
    $r = Probe ([Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('HttpShare:' + $pw)))
    if ($r[0] -ge 200 -and $r[0] -lt 400) { $ok = $true; break }
    if ($r[0] -eq 403) { Fail '密码错误次数过多，已被封锁 2 小时（在 App 里重启服务可立即解除）。' }
    if ($r[0] -ne 401) { Fail ('验证失败：HTTP ' + $r[0] + ' ' + $r[2]) }
    if ($env:HTTPSHARE_PW) { Fail '密码错误。' }
    Say '密码错误，请重新输入（连续输错 3 次会被封锁 2 小时）。' 'Red'
}
if (-not $ok) { Fail '密码错误，已停止尝试。' }

# 5. 选空闲盘符并映射
$used = @([IO.DriveInfo]::GetDrives() | ForEach-Object { $_.Name.Substring(0, 1) })
foreach ($l in (& "$Sys\net.exe" use 2>$null)) { if ($l -match '\b([A-Z]):\s') { $used += $Matches[1] } }
$drv = $null
foreach ($c in 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H') {
    if ($used -notcontains $c) { $drv = "${c}:"; break }
}
if (-not $drv) { Fail '没有空闲的盘符（H 到 Z 都已占用）。' }
$ErrorActionPreference = 'Continue'
$out = & "$Sys\net.exe" use $drv $DavUrl $pw /user:HttpShare /persistent:$Persist 2>&1
$rc = $LASTEXITCODE
$pw = $null
if ($rc -ne 0) { Fail ('挂载失败：' + (($out | ForEach-Object { "$_".Trim() } | Where-Object { $_ }) -join ' ')) }
Write-Host
Say "已挂载为 $drv 盘，正在打开……" 'Green'
OpenDrive $drv
if ($Note) { Say $Note }
Say '断开：在“此电脑”里右键该盘符，选择“断开连接”。'
exit 0
