plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.jiemo9527.httpshare'
    compileSdk 35

    defaultConfig {
        applicationId 'io.github.jiemo9527.httpshare'
        minSdk 29
        targetSdk 35
        versionCode 5
        versionName '0.4.1'
    }

    packagingOptions {
        jniLibs {
            // cloudflared 必须解压到 nativeLibraryDir 才能执行
            useLegacyPackaging true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
